upstream dashboard {
  server dashboard:3000;
}

upstream broker {
  server broker:4000;
}

server {
  listen 80;
  server_name pixelium.duckdns.org;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name pixelium.duckdns.org;

  ssl_certificate /etc/letsencrypt/live/pixelium.duckdns.org/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/pixelium.duckdns.org/privkey.pem;

  client_max_body_size 12m;

  location / {
    proxy_pass http://dashboard;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /broker/ {
    proxy_pass http://broker/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
