export interface Product {
  sku: string;
  name: string;
  category: string;
  priceCents: number;
  description: string;
  refundable: boolean;
  inStock: number;
  imageUrl?: string;
}

/** Curated store catalog — upserted to MySQL on every broker start. */
export const STORE_CATALOG: Product[] = [
  {
    sku: 'SHOE-RED-HIGH',
    name: 'Classic Red High-Top Sneakers',
    category: 'footwear',
    priceCents: 12999,
    description:
      'Bold red high-top sneakers with padded collar and grippy rubber sole. Lightweight for running, training, and everyday wear.',
    refundable: true,
    inStock: 12,
  },
  {
    sku: 'SHOE-RUN-BLK',
    name: 'Performance Running Shoes (Black)',
    category: 'footwear',
    priceCents: 14999,
    description: 'Breathable mesh upper, responsive foam midsole, and durable outsole for road and track running.',
    refundable: true,
    inStock: 18,
  },
  {
    sku: 'SHOE-WALK-WHT',
    name: 'Everyday Walkers (White)',
    category: 'footwear',
    priceCents: 8999,
    description: 'Comfort-first walking shoes with cushioned insole and flexible sole for all-day wear.',
    refundable: true,
    inStock: 24,
  },
  {
    sku: 'JACKET-GREEN-M',
    name: 'Waterproof Trail Jacket (Green, M)',
    category: 'outerwear',
    priceCents: 18999,
    description: 'Seam-sealed hood, breathable lining, and packable fit for hiking and winter commutes.',
    refundable: true,
    inStock: 5,
  },
  {
    sku: 'JACKET-PUFF-L',
    name: 'Lightweight Puffer Jacket (L)',
    category: 'outerwear',
    priceCents: 15999,
    description: '700-fill synthetic insulation, water-resistant shell, and zip pockets. Ideal for cold mornings.',
    refundable: true,
    inStock: 9,
  },
  {
    sku: 'HOODIE-GRY-XL',
    name: 'Organic Cotton Hoodie (Grey, XL)',
    category: 'apparel',
    priceCents: 6499,
    description: 'Soft brushed fleece interior, kangaroo pocket, and relaxed fit. GOTS-certified cotton.',
    refundable: true,
    inStock: 32,
  },
  {
    sku: 'TEE-BASIC-BLK',
    name: 'Essential Crew Tee (Black)',
    category: 'apparel',
    priceCents: 2499,
    description: 'Pre-shrunk cotton tee with reinforced neckline. Wardrobe staple in classic black.',
    refundable: true,
    inStock: 80,
  },
  {
    sku: 'PHONE-17-PRO',
    name: 'PixelPhone 17 Pro (256GB)',
    category: 'electronics',
    priceCents: 169999,
    description: '6.7" OLED display, triple-camera system, all-day battery, and 5G. One-year warranty included.',
    refundable: false,
    inStock: 20,
  },
  {
    sku: 'HEADPHONES-NC',
    name: 'Noise-Canceling Headphones',
    category: 'electronics',
    priceCents: 34999,
    description: '40-hour battery, adaptive ANC, Bluetooth 5.3, and memory-foam ear cushions with travel case.',
    refundable: true,
    inStock: 30,
  },
  {
    sku: 'EARBUDS-PRO',
    name: 'Wireless Earbuds Pro',
    category: 'electronics',
    priceCents: 19999,
    description: 'Active noise cancellation, IPX5 sweat resistance, and wireless charging case with 28h total playtime.',
    refundable: true,
    inStock: 45,
  },
  {
    sku: 'WATCH-SPORT-01',
    name: 'Sport Smartwatch GPS',
    category: 'electronics',
    priceCents: 27999,
    description: 'Heart-rate monitoring, GPS routes, sleep tracking, and 7-day battery. Swim-proof to 50m.',
    refundable: true,
    inStock: 15,
  },
  {
    sku: 'TABLET-11',
    name: 'PixelTab 11" (128GB)',
    category: 'electronics',
    priceCents: 89999,
    description: '11-inch LCD, stylus support, dual speakers, and all-day battery for work and entertainment.',
    refundable: false,
    inStock: 11,
  },
  {
    sku: 'LAPTOP-ULTRA',
    name: 'UltraBook 14" (512GB SSD)',
    category: 'electronics',
    priceCents: 129999,
    description: '14" retina display, 16GB RAM, backlit keyboard, and 18-hour battery for productivity on the go.',
    refundable: false,
    inStock: 8,
  },
  {
    sku: 'BOOK-AI-AGENTS',
    name: 'Building Agentic Systems',
    category: 'books',
    priceCents: 4599,
    description: 'Guide to multi-agent architectures, RAG pipelines, and consent-aware commerce. Paperback, 320 pages.',
    refundable: true,
    inStock: 100,
  },
  {
    sku: 'BOOK-DESIGN',
    name: 'Design Systems Handbook',
    category: 'books',
    priceCents: 3899,
    description: 'Practical patterns for tokens, components, and scalable UI libraries. Full-color paperback.',
    refundable: true,
    inStock: 55,
  },
  {
    sku: 'BAG-LEATHER-TOTE',
    name: 'Leather Tote Bag',
    category: 'accessories',
    priceCents: 11999,
    description: 'Full-grain leather tote with interior laptop sleeve, magnetic closure, and reinforced handles.',
    refundable: true,
    inStock: 14,
  },
  {
    sku: 'BAG-BACKPACK-URB',
    name: 'Urban Commuter Backpack',
    category: 'accessories',
    priceCents: 7999,
    description: 'Water-resistant fabric, padded laptop compartment, and ergonomic straps for daily commutes.',
    refundable: true,
    inStock: 22,
  },
  {
    sku: 'WALLET-SLIM',
    name: 'Slim RFID Wallet',
    category: 'accessories',
    priceCents: 3499,
    description: 'Minimalist card holder with RFID blocking and quick-access thumb slot. Holds 6–8 cards.',
    refundable: true,
    inStock: 40,
  },
  {
    sku: 'SUNGLASS-AV',
    name: 'Classic Aviator Sunglasses',
    category: 'accessories',
    priceCents: 8999,
    description: 'Polarized lenses, UV400 protection, and lightweight metal frame with soft nose pads.',
    refundable: true,
    inStock: 19,
  },
  {
    sku: 'BOTTLE-INSUL',
    name: 'Insulated Water Bottle (750ml)',
    category: 'home',
    priceCents: 2999,
    description: 'Double-wall stainless steel keeps drinks cold 24h or hot 12h. Leak-proof flip lid.',
    refundable: true,
    inStock: 60,
  },
  {
    sku: 'MUG-CERAMIC',
    name: 'Hand-Glazed Ceramic Mug',
    category: 'home',
    priceCents: 1899,
    description: '350ml artisan mug, microwave and dishwasher safe. Matte finish with speckled glaze.',
    refundable: true,
    inStock: 75,
  },
  {
    sku: 'LAMP-DESK-LED',
    name: 'Adjustable Desk Lamp LED',
    category: 'home',
    priceCents: 5499,
    description: 'Touch dimmer, warm-to-cool color temperature, and USB charging port in the base.',
    refundable: true,
    inStock: 28,
  },
  {
    sku: 'BLANKET-WOOL',
    name: 'Merino Wool Throw Blanket',
    category: 'home',
    priceCents: 8999,
    description: 'Soft merino blend, machine washable, and perfect for sofas and reading nooks.',
    refundable: true,
    inStock: 16,
  },
  {
    sku: 'YOGA-MAT-PRO',
    name: 'Pro Yoga Mat (6mm)',
    category: 'fitness',
    priceCents: 4999,
    description: 'Non-slip surface, alignment guides, and carrying strap. Eco-friendly TPE material.',
    refundable: true,
    inStock: 35,
  },
  {
    sku: 'DUMBBELL-10',
    name: 'Neoprene Dumbbell Pair (10 lb)',
    category: 'fitness',
    priceCents: 4499,
    description: 'Hex-shaped neoprene-coated dumbbells with contoured grip for home workouts.',
    refundable: true,
    inStock: 26,
  },
  {
    sku: 'RESIST-BAND-SET',
    name: 'Resistance Band Set (5 levels)',
    category: 'fitness',
    priceCents: 2799,
    description: 'Five color-coded bands, door anchor, handles, and storage bag for full-body training.',
    refundable: true,
    inStock: 50,
  },
  {
    sku: 'COFFEE-BEANS-1KG',
    name: 'Single-Origin Coffee Beans (1 kg)',
    category: 'grocery',
    priceCents: 3299,
    description: 'Medium roast Arabica from Colombia. Notes of chocolate and citrus. Roasted weekly.',
    refundable: true,
    inStock: 42,
  },
  {
    sku: 'TEA-GREEN-100',
    name: 'Organic Green Tea (100 bags)',
    category: 'grocery',
    priceCents: 1499,
    description: 'Sencha green tea in compostable sachets. Light, grassy flavor with gentle caffeine.',
    refundable: true,
    inStock: 90,
  },
  {
    sku: 'SKIN-MOIST-50',
    name: 'Daily Moisturizer SPF 30 (50ml)',
    category: 'beauty',
    priceCents: 2499,
    description: 'Lightweight daily moisturizer with broad-spectrum SPF 30. Fragrance-free, non-comedogenic.',
    refundable: true,
    inStock: 38,
  },
  {
    sku: 'LIP-BALM-3PK',
    name: 'Hydrating Lip Balm (3-pack)',
    category: 'beauty',
    priceCents: 999,
    description: 'Shea butter and vitamin E formula. Vanilla, mint, and unscented variants.',
    refundable: true,
    inStock: 65,
  },
];

export const FEATURED_SKUS = [
  'SHOE-RED-HIGH',
  'HEADPHONES-NC',
  'PHONE-17-PRO',
  'JACKET-GREEN-M',
  'WATCH-SPORT-01',
  'BAG-LEATHER-TOTE',
  'EARBUDS-PRO',
  'YOGA-MAT-PRO',
];
